keys:
  - &admin_age "age14aaw06ykpmrzgp56gyfhu2c0eh4w0k4aavq594tpym7j978hl5cs7qvccc"
  - &laptop_old "age1r2vxuh7f2lt3v437nhu607tpevt8a0rwxeajruyj3zg6lyfta3wq268m4f"

creation_rules:
  - path_regex: secrets/.*
    key_groups:
      - age:
        - *admin_age
        - *laptop_old
